# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "laravo"
client_id = "4b2e458d38317fae192364023a4d48fd"
application_url = "https://apply-mountain-antivirus-vary.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://apply-mountain-antivirus-vary.trycloudflare.com/auth/callback",
  "https://apply-mountain-antivirus-vary.trycloudflare.com/auth/shopify/callback",
  "https://apply-mountain-antivirus-vary.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mr-quvvatov.myshopify.com"
